name: Continuous Integration
on:  [push]
jobs:
  call-continuous-integration-reusable:
    uses: raju-b72/github-reusable-workflows/.github/workflows/ci.yml@main
    with:
      project-name: expense-backend
      npm_install: true
    secrets: inherit

#9